import * as fs from "fs/promises";
import { join } from "path";
import * as vscode from "vscode";

export async function saveDossier(data: any): Promise<void> {
  const workspaceFolders = vscode.workspace.workspaceFolders;
  if (!workspaceFolders) {
    vscode.window.showErrorMessage("No workspace folder open.");
    return;
  }

  const projectRoot = workspaceFolders[0].uri.fsPath;

  // 1. Save stack.json
  const dossierDir = join(projectRoot, ".architect-guardian");
  try {
    await fs.mkdir(dossierDir, { recursive: true });
    await fs.writeFile(
      join(dossierDir, "stack.json"),
      JSON.stringify(data, null, 2),
      "utf-8",
    );
  } catch (err: any) {
    vscode.window.showErrorMessage(`Failed to save stack.json: ${err.message}`);
  }

  // 2. Save .copilot/copilot-instructions.md
  const copilotDir = join(projectRoot, ".copilot");
  const instructionsPath = join(copilotDir, "copilot-instructions.md");

  const instructions = `
# Project Architectural Context: ${data.framework || data.language}

This project has been analyzed by **Architect Guardian**. Use the following context to guide your decisions.

## Technical Stack
- **Language**: ${data.language}
- **Framework**: ${data.framework}
- **Package Manager**: ${data.packageManager}
- **Architectural Pattern**: ${data.architecturalPattern || "Standard/Layered"}

## Architecture Analysis
${data.reasoning}

## Guidelines
1. Adhere to the ${data.architecturalPattern || "standards"} patterns identified above.
2. When creating new files, follow the existing directory topology.
3. If Docker is present (${data.hasDocker}), ensure any new services include appropriate Dockerfiles.
4. If CI/CD is present (${data.hasCI}), ensure new features are compatible with the existing pipeline.

---
*Generated by Architect Guardian*
`.trim();

  try {
    await fs.mkdir(copilotDir, { recursive: true });
    await fs.writeFile(instructionsPath, instructions, "utf-8");
    vscode.window.showInformationMessage(
      "Architecture Dossier generated and saved to .copilot/copilot-instructions.md",
    );
  } catch (err: any) {
    vscode.window.showErrorMessage(
      `Failed to save copilot-instructions.md: ${err.message}`,
    );
  }
}
